### PR TITLE
Fix no such file or dir error.

### LINKED ISSUE #42: `(Errno::ENOENT) No such file or directory` error with Logstash 8.10+ versions
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
  - 8.10+ versions, basically issue started after upgrading JRuby to 9.4.2.0
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
4. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
5. How was the Logstash Plugin installed
  - embedded 3.3.1 version 

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`): embeded
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Use following kafka output
```
kafka {
  bootstrap_servers => "{host}:9092"
  topics => "logstash-test"
  codec => avro {
    schema_uri => "http://127.0.0.1:8081/my-schema"
  }
}
```
 2. Run with 8.10+ versions
 3. Error will be raised during the plugin register

**Note that, issue doesn't happen up to LS 8.9.2 versions.**

**Provide logs (if relevant)**:
```
[2023-10-06T15:33:05,369][INFO ][logstash.runner          ] Log4j configuration path used is: /Users/mashhur/Dev/elastic/temp/logstash/logstash-8.10.2/config/log4j2.properties
[2023-10-06T15:33:05,397][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"8.10.2", "jruby.version"=>"jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 17.0.8+7 on 17.0.8+7 +indy +jit [x86_64-darwin]"}
[2023-10-06T15:33:05,409][INFO ][logstash.runner          ] JVM bootstrap flags: [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djruby.compile.invokedynamic=true, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Djruby.regexp.interruptible=true, -Djdk.io.File.enableADS=true, --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.nio.channels=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.management/sun.management=ALL-UNNAMED]
[2023-10-06T15:33:05,558][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-10-06T15:33:06,976][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
[2023-10-06T15:33:07,464][INFO ][org.reflections.Reflections] Reflections took 146 ms to scan 1 urls, producing 132 keys and 464 values
Opening an URI: http://127.0.0.1:8081
[2023-10-06T15:33:08,012][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (ENOENT) No such file or directory - http://127.0.0.1:8081", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:120)", "org.logstash.execution.AbstractPipelineExt.initialize(AbstractPipelineExt.java:186)", "org.logstash.execution.AbstractPipelineExt$INVOKER$i$initialize.call(AbstractPipelineExt$INVOKER$i$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:847)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1318)", "org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:139)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:367)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:452)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:92)", "org.jruby.RubyClass.newInstance(RubyClass.java:931)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:452)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:92)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:367)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:88)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:238)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:225)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:228)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:516)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:293)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:328)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.Block.call(Block.java:143)", "org.jruby.RubyProc.call(RubyProc.java:352)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:110)", "java.base/java.lang.Thread.run(Thread.java:833)"]}
[2023-10-06T15:33:08,041][INFO ][logstash.runner          ] Logstash shut down.
[2023-10-06T15:33:08,051][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:795) ~[jruby.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:758) ~[jruby.jar:?]
	at Users.mashhur.Dev.elastic.temp.logstash.logstash_minus_8_dot_10_dot_2.lib.bootstrap.environment.<main>(/Users/mashhur/Dev/elastic/temp/logstash/logstash-8.10.2/lib/bootstrap/environment.rb:90) ~[?:?]
```

### PR DESCRIPTION
**Pull request by mashhurs**
### Description
Logstash 8.10+ versions fail with `(Errno::ENOENT) No such file or directory` error. It is happening after Ruby 2.6 to Ruby 3.1 upgrade through JRuby.
As a solution, it seems there are multiple discussions ([1](https://bugs.ruby-lang.org/issues/15893), [2](https://bugs.ruby-lang.org/issues/19630)) and current solution is to change `open` to `URI.open`

- Closes #42 

### Test
- use `kafka-output` plugin with `avro-codec`
```
input {
  stdin {}
}

output {
    stdout {
        codec => rubydebug
    }
    kafka {
        bootstrap_servers => "192.168.1.66:9092"
        codec => avro {
            schema_uri => "http://127.0.0.1:8081/my-schema"
            #schema_uri => "/static/avro-sample.xml"
            encoding => "binary"
        }
        topic_id => "sample"
    }
}
```
- output logs
```
[2023-10-13T11:01:11,713][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"avro", :type=>"codec", :class=>LogStash::Codecs::Avro}
[2023-10-13T11:01:11,714][DEBUG][logstash.codecs.avro     ] config LogStash::Codecs::Avro/@encoding = "binary"
[2023-10-13T11:01:11,714][DEBUG][logstash.codecs.avro     ] config LogStash::Codecs::Avro/@schema_uri = "/Users/mashhur/Dev/elastic/temp/simple-nodejs/static/avro-sample.xml"
[2023-10-13T11:01:11,715][DEBUG][logstash.codecs.avro     ] config LogStash::Codecs::Avro/@id = "96ef7bd9-34cc-4a71-b184-c6087411fa3c"
[2023-10-13T11:01:11,715][DEBUG][logstash.codecs.avro     ] config LogStash::Codecs::Avro/@enable_metric = true
[2023-10-13T11:01:11,715][DEBUG][logstash.codecs.avro     ] config LogStash::Codecs::Avro/@tag_on_failure = false
```

### CODE REVIEW

File: lib/logstash/codecs/avro.rb [hunk 1]
```diff
@@ -85,7 +85,7 @@ class LogStash::Codecs::Avro < LogStash::Codecs::Base
   config :target, :validate => :field_reference
 
   def open_and_read(uri_string)
-    open(uri_string).read
+    URI.open(uri_string, &:read)
```
Comment (mashhurs) [inline lib/logstash/codecs/avro.rb:88]: review note: in the doc we don't mention about `ftp` URIs. I do think this will be separate from current bug fix change but if we need to support `ftp`, we need to include `net/ftp` dependency as [`open-uri` requires](https://github.com/ruby/open-uri/blob/b41d2c63de32390c127056590e7a3eda263e2eb8/lib/open-uri.rb#L755-L757).

**Review by jsvd — APPROVED** [review]
LGTM
